project:
  type: website
  output-dir: docs

website:
  title: "Herpor's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Text Analysis
        href: text-analysis.qmd
      - text: Maps
        href: maps.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full